Updated slugify documentation
Unicode, case-sensitive reference setting causes error below.

```
yaml.constructor.ConstructorError: expected a mapping node, but found scalar
```

Update related sections in the documentation to address this issue.

Newer Python-Markdown has `slugify_unicode` built-in, so this

```yaml
markdown_extensions:
  - toc:
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
```

also works for case-insensitive use cases.

Fixes: ee1e675da613 ("Update slug reference")